"""Minimal i18n for SEO-facing / static UI strings.

Not a full babel-style setup: locale is decided purely by which URL prefix a
request came through (see /de blueprint registration in hitch/__init__.py),
and translated strings are looked up by their English text as the key (no
separate msgid namespace to keep in sync). This deliberately does NOT cover
database content (ride comments, place names from OSM/Photon, usernames) --
those are left as-is in every language, see CLAUDE.md.

Translations live in <lang>.json, keyed by the exact English source string,
generated by hitch/scripts/translate_strings.py via the OpenAI API. A string
with no entry (not yet translated, or lang == "en") falls back to itself.
"""

import json
import os

from flask import g

SUPPORTED_LANGUAGES = (
    "en", "de", "fr", "pt", "ru", "pl", "es", "it", "hr", "cs", "et", "hu", "zh", "ja", "ro",
    "bg", "da", "el", "fi", "ka", "lt", "lv", "mn", "nl", "no", "sk", "sl", "sr", "sv", "tr", "uk",
)

# Each language's own name for itself, for the switcher UI (hitch/templates/map.html).
# Deliberately NOT translated (an endonym is shown the same in every language) --
# a German visitor still needs to recognize "English", not read a translation of it.
LANGUAGE_ENDONYMS = {
    "en": "English",
    "de": "Deutsch",
    "fr": "Français",
    "pt": "Português",
    "ru": "Русский",
    "pl": "Polski",
    "es": "Español",
    "it": "Italiano",
    "hr": "Hrvatski",
    "cs": "Čeština",
    "et": "Eesti",
    "hu": "Magyar",
    "zh": "中文",
    "ja": "日本語",
    "ro": "Română",
    "bg": "Български",
    "da": "Dansk",
    "el": "Ελληνικά",
    "fi": "Suomi",
    "ka": "ქართული",
    "lt": "Lietuvių",
    "lv": "Latviešu",
    "mn": "Монгол",
    "nl": "Nederlands",
    "no": "Norsk",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sr": "Српски",
    "sv": "Svenska",
    "tr": "Türkçe",
    "uk": "Українська",
}

# One representative flag per language for the switcher UI. A language isn't a
# country, so this is inherently a simplification (fr could be many Francophone
# flags, pt could be BR) -- picked the flag most visitors would associate with
# each language first, same tradeoff every flag-based language picker makes.
LANGUAGE_FLAGS = {
    "en": "🇬🇧",
    "de": "🇩🇪",
    "fr": "🇫🇷",
    "pt": "🇵🇹",
    "ru": "🇷🇺",
    "pl": "🇵🇱",
    "es": "🇪🇸",
    "it": "🇮🇹",
    "hr": "🇭🇷",
    "cs": "🇨🇿",
    "et": "🇪🇪",
    "hu": "🇭🇺",
    "zh": "🇨🇳",
    "ja": "🇯🇵",
    "ro": "🇷🇴",
    "bg": "🇧🇬",
    "da": "🇩🇰",
    "el": "🇬🇷",
    "fi": "🇫🇮",
    "ka": "🇬🇪",
    "lt": "🇱🇹",
    "lv": "🇱🇻",
    "mn": "🇲🇳",
    "nl": "🇳🇱",
    "no": "🇳🇴",
    "sk": "🇸🇰",
    "sl": "🇸🇮",
    "sr": "🇷🇸",
    "sv": "🇸🇪",
    "tr": "🇹🇷",
    "uk": "🇺🇦",
}

_TRANSLATIONS_DIR = os.path.dirname(__file__)
_cache = {}


def _load(lang):
    if lang not in _cache:
        path = os.path.join(_TRANSLATIONS_DIR, f"{lang}.json")
        try:
            with open(path, encoding="utf-8") as f:
                _cache[lang] = json.load(f)
        except (OSError, ValueError):
            _cache[lang] = {}
    return _cache[lang]


def current_lang():
    return getattr(g, "lang", "en")


def client_translations():
    """The current language's whole dict, for map.js's JS-side t() (see map.js
    and client_translations_json() in hitch/__init__.py). Empty for English so
    the page never ships a no-op translations blob."""
    lang = current_lang()
    return _load(lang) if lang != "en" else {}


def t(text, **kwargs):
    """Translate `text` (the English source string, used as the lookup key)
    into the current request's language, then apply any {placeholder} values.

    Falls back to the English source whenever the language is "en", the
    string has no translation yet, or the translation file is missing --
    so it's always safe to wrap a string in t() before its translation
    exists.
    """
    lang = current_lang()
    if lang != "en":
        text = _load(lang).get(text, text)
    return text.format(**kwargs) if kwargs else text
