"""Minimal i18n for SEO-facing / static UI strings.

Not a full babel-style setup: locale is decided purely by which URL prefix a
request came through (see /de blueprint registration in hitch/__init__.py),
and translated strings are looked up by their English text as the key (no
separate msgid namespace to keep in sync). This deliberately does NOT cover
database content (ride comments, place names from OSM/Photon, usernames) --
those are left as-is in every language, see CLAUDE.md.

Translations live in <lang>.json, keyed by the exact English source string,
generated by hitch/scripts/translate_strings.py via the OpenAI API. A string
with no entry (not yet translated, or lang == "en") falls back to itself.
"""

import json
import os

from flask import g

SUPPORTED_LANGUAGES = ("en", "de")

_TRANSLATIONS_DIR = os.path.dirname(__file__)
_cache = {}


def _load(lang):
    if lang not in _cache:
        path = os.path.join(_TRANSLATIONS_DIR, f"{lang}.json")
        try:
            with open(path, encoding="utf-8") as f:
                _cache[lang] = json.load(f)
        except (OSError, ValueError):
            _cache[lang] = {}
    return _cache[lang]


def current_lang():
    return getattr(g, "lang", "en")


def client_translations():
    """The current language's whole dict, for map.js's JS-side t() (see map.js
    and client_translations_json() in hitch/__init__.py). Empty for English so
    the page never ships a no-op translations blob."""
    lang = current_lang()
    return _load(lang) if lang != "en" else {}


def t(text, **kwargs):
    """Translate `text` (the English source string, used as the lookup key)
    into the current request's language, then apply any {placeholder} values.

    Falls back to the English source whenever the language is "en", the
    string has no translation yet, or the translation file is missing --
    so it's always safe to wrap a string in t() before its translation
    exists.
    """
    lang = current_lang()
    if lang != "en":
        text = _load(lang).get(text, text)
    return text.format(**kwargs) if kwargs else text
