"""International vehicle registration codes (the codes that appear on
license plates, e.g. "D" for Germany, "GB" for the United Kingdom, "RUS"
for Russia) mapped to ISO 3166-1 alpha-2 country codes (the form we store
in the Hitchhiking Data Standard).

Sourced from the United Nations distinguishing signs convention plus
common national plate codes for countries that aren't covered there.
Stored as a list of (iso_alpha_2, plate_code, country_name) tuples so
the UI can let the user search by the code they see on the plate.
"""

# (iso_alpha_2, plate_code, country_name)
LICENSE_PLATE_COUNTRY_CHOICES = [
    ("AL", "AL", "Albania"),
    ("DZ", "DZ", "Algeria"),
    ("AD", "AND", "Andorra"),
    ("AR", "RA", "Argentina"),
    ("AM", "ARM", "Armenia"),
    ("AU", "AUS", "Australia"),
    ("AT", "A", "Austria"),
    ("AZ", "AZ", "Azerbaijan"),
    ("BD", "BD", "Bangladesh"),
    ("BY", "BY", "Belarus"),
    ("BE", "B", "Belgium"),
    ("BO", "BOL", "Bolivia"),
    ("BA", "BIH", "Bosnia and Herzegovina"),
    ("BR", "BR", "Brazil"),
    ("BG", "BG", "Bulgaria"),
    ("KH", "K", "Cambodia"),
    ("CA", "CDN", "Canada"),
    ("CL", "RCH", "Chile"),
    ("CN", "CHN", "China"),
    ("CO", "CO", "Colombia"),
    ("CR", "CR", "Costa Rica"),
    ("HR", "HR", "Croatia"),
    ("CU", "C", "Cuba"),
    ("CY", "CY", "Cyprus"),
    ("CZ", "CZ", "Czech Republic"),
    ("DK", "DK", "Denmark"),
    ("DO", "DOM", "Dominican Republic"),
    ("EC", "EC", "Ecuador"),
    ("EG", "ET", "Egypt"),
    ("SV", "ES", "El Salvador"),
    ("EE", "EST", "Estonia"),
    ("FI", "FIN", "Finland"),
    ("FR", "F", "France"),
    ("GE", "GE", "Georgia"),
    ("DE", "D", "Germany"),
    ("GR", "GR", "Greece"),
    ("GT", "GCA", "Guatemala"),
    ("HN", "HN", "Honduras"),
    ("HU", "H", "Hungary"),
    ("IS", "IS", "Iceland"),
    ("IN", "IND", "India"),
    ("ID", "RI", "Indonesia"),
    ("IR", "IR", "Iran"),
    ("IQ", "IRQ", "Iraq"),
    ("IE", "IRL", "Ireland"),
    ("IL", "IL", "Israel"),
    ("IT", "I", "Italy"),
    ("JM", "JA", "Jamaica"),
    ("JP", "J", "Japan"),
    ("JO", "JOR", "Jordan"),
    ("KZ", "KZ", "Kazakhstan"),
    ("KE", "EAK", "Kenya"),
    ("KR", "ROK", "Korea (Republic of)"),
    ("KW", "KWT", "Kuwait"),
    ("KG", "KS", "Kyrgyzstan"),
    ("LV", "LV", "Latvia"),
    ("LB", "RL", "Lebanon"),
    ("LI", "FL", "Liechtenstein"),
    ("LT", "LT", "Lithuania"),
    ("LU", "L", "Luxembourg"),
    ("MK", "MK", "North Macedonia"),
    ("MY", "MAL", "Malaysia"),
    ("MT", "M", "Malta"),
    ("MX", "MEX", "Mexico"),
    ("MD", "MD", "Moldova"),
    ("MC", "MC", "Monaco"),
    ("MN", "MGL", "Mongolia"),
    ("ME", "MNE", "Montenegro"),
    ("MA", "MA", "Morocco"),
    ("NL", "NL", "Netherlands"),
    ("NZ", "NZ", "New Zealand"),
    ("NI", "NIC", "Nicaragua"),
    ("NG", "WAN", "Nigeria"),
    ("NO", "N", "Norway"),
    ("PK", "PK", "Pakistan"),
    ("PA", "PA", "Panama"),
    ("PY", "PY", "Paraguay"),
    ("PE", "PE", "Peru"),
    ("PH", "RP", "Philippines"),
    ("PL", "PL", "Poland"),
    ("PT", "P", "Portugal"),
    ("QA", "Q", "Qatar"),
    ("RO", "RO", "Romania"),
    ("RU", "RUS", "Russia"),
    ("SM", "RSM", "San Marino"),
    ("SA", "SA", "Saudi Arabia"),
    ("RS", "SRB", "Serbia"),
    ("SG", "SGP", "Singapore"),
    ("SK", "SK", "Slovakia"),
    ("SI", "SLO", "Slovenia"),
    ("ZA", "ZA", "South Africa"),
    ("ES", "E", "Spain"),
    ("LK", "CL", "Sri Lanka"),
    ("SE", "S", "Sweden"),
    ("CH", "CH", "Switzerland"),
    ("SY", "SYR", "Syria"),
    ("TW", "RC", "Taiwan"),
    ("TJ", "TJ", "Tajikistan"),
    ("TZ", "EAT", "Tanzania"),
    ("TH", "T", "Thailand"),
    ("TN", "TN", "Tunisia"),
    ("TR", "TR", "Turkey"),
    ("TM", "TM", "Turkmenistan"),
    ("UA", "UA", "Ukraine"),
    ("AE", "UAE", "United Arab Emirates"),
    ("GB", "GB", "United Kingdom"),
    ("US", "USA", "United States"),
    ("UY", "ROU", "Uruguay"),
    ("UZ", "UZ", "Uzbekistan"),
    ("VA", "V", "Vatican City"),
    ("VE", "YV", "Venezuela"),
    ("VN", "VN", "Vietnam"),
]
