"""Photo attachments for a ride: validation, storage on disk, and lookup.

Where the bytes live: `dist/ride-images/<yyyy>/<mm>/<uuid>.jpg`. `dist/` is the right
home for three independent reasons — it is bind-mounted into the container (so uploads
survive an image rebuild, and a deploy's `git reset --hard` cannot touch them), the whole
directory is gitignored (so nothing a visitor uploads can reach the repository), and the
catch-all route already serves it, so no extra endpoint is needed.

Every upload is decoded and re-encoded through Pillow rather than stored as received.
That is the entire security model here: the bytes we serve back are ones Pillow wrote, so
a file that is simultaneously a valid image and a valid HTML/script payload cannot
survive the round trip. Re-encoding also drops EXIF, which matters for consent as much as
for size — a phone photo carries GPS coordinates and a device serial, and someone
attaching a picture of a slip road is not choosing to publish where they live.

A photo is uploaded the instant it is picked, not when the form is submitted, and lands
under the form's random `draft_token` until the submit claims it. That is not a nicety:
the ride form navigates the whole page away to the map to pick a pickup point, and a
`<input type=file>` selection cannot survive a navigation — nor can a second visit to the
file picker keep the first one's files, since opening it replaces the whole FileList.
Holding files in the browser until submit silently loses them both ways.
"""

import logging
import os
import re
import uuid
from datetime import datetime, timedelta, timezone
from io import BytesIO

from PIL import Image, ImageOps, UnidentifiedImageError

from hitch.extensions import db
from hitch.helpers import dirs
from hitch.models import RideImage

logger = logging.getLogger(__name__)

# Requirement: at most three photos per ride. Enforced here rather than only in the
# browser, and counted against photos that already exist, so an edit cannot walk the
# total up three at a time.
MAX_IMAGES_PER_RIDE = 3

# Per-file cap on the *uploaded* bytes. A modern phone photo is 3-8 MB; 12 MB leaves room
# for that without letting one request buffer an arbitrary amount of memory. The
# app-wide MAX_CONTENT_LENGTH (settings.py) is the outer guard for the whole request.
MAX_UPLOAD_BYTES = 12 * 1024 * 1024

# Longest side of the stored image. A ride photo is looked at on a phone or inline on the
# ride page; anything beyond this is bandwidth nobody sees. ~1600px keeps a stored JPEG
# in the low hundreds of KB.
MAX_DIMENSION = 1600
JPEG_QUALITY = 82

# Decompression-bomb guard: a 5 KB PNG can declare a 100k x 100k canvas, which Pillow
# would happily try to allocate. Pillow's own default only *warns* at ~89 Mpx; be
# explicit and refuse well below anything a real camera produces (50 Mpx ≈ 8600x5800).
Image.MAX_IMAGE_PIXELS = 50_000_000

# Formats we are willing to decode. Everything is re-encoded to JPEG regardless, so this
# list is about what a browser's file picker realistically hands us, not about output.
ALLOWED_FORMATS = {"JPEG", "PNG", "WEBP", "GIF", "BMP", "TIFF"}

RIDE_IMAGES_SUBDIR = "ride-images"

# The public URL prefix. dist/ride-images/<rel> is served by the catch-all route at
# /ride-images/<rel> — the two must stay in step.
RIDE_IMAGES_URL_PREFIX = "/" + RIDE_IMAGES_SUBDIR

# How long a photo may sit unclaimed under a draft token before it is swept. Long enough
# that someone can fill the form, wander off to pick a pickup point on the map, get
# distracted, and still come back to it; short enough that an abandoned form (or someone
# using the upload endpoint as free image hosting) doesn't accumulate.
DRAFT_TTL = timedelta(hours=24)

# Draft tokens are generated by the browser (crypto.randomUUID), so validate the shape
# before it reaches a query — it is the key that grants access to a draft's photos.
_DRAFT_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{8,64}$")


def valid_draft_token(token):
    """The token if it looks like one we issued, else None."""
    token = (token or "").strip()
    return token if _DRAFT_TOKEN_RE.match(token) else None


class RideImageError(ValueError):
    """A rejected upload.

    Subclasses ValueError on purpose: the /ride POST handler already turns ValueError
    into "bad input, do not retry" (400 for the in-ride JSON client), which is exactly
    the right classification for a file the user must replace.
    """


class PreparedImage:
    """A validated, re-encoded image held in memory until the ride has a d tag."""

    __slots__ = ("data", "width", "height")

    def __init__(self, data, width, height):
        self.data = data
        self.width = width
        self.height = height


def ride_images_dir():
    return os.path.join(dirs["dist"], RIDE_IMAGES_SUBDIR)


def image_url(filename):
    """Public URL for a stored photo, e.g. "/ride-images/2026/07/<uuid>.jpg"."""
    return f"{RIDE_IMAGES_URL_PREFIX}/{filename}"


def images_for_ride(d_tag):
    """This ride's photos, oldest first (upload order is the display order)."""
    if not d_tag:
        return []
    return db.session.query(RideImage).filter_by(ride_d_tag=d_tag).order_by(RideImage.id.asc()).all()


def attach_ride_images(ride_cards):
    """Fill each ride card's `images` with its photo URLs, in one query for the whole list.

    The shared _ride_card.html macro shows a ride's photos, and a list renders up to a
    hundred cards — asking per card would be a hundred round trips for a feature most
    rides don't use yet. Cards with no photos get an empty list, so the template can test
    the key without a guard.
    """
    tags = [d for d in dict.fromkeys(card.get("d_tag") for card in ride_cards) if d]
    urls = {}
    if tags:
        rows = db.session.query(RideImage).filter(RideImage.ride_d_tag.in_(tags)).order_by(RideImage.id.asc()).all()
        for row in rows:
            urls.setdefault(row.ride_d_tag, []).append(image_url(row.filename))
    for card in ride_cards:
        card["images"] = urls.get(card.get("d_tag"), [])
    return ride_cards


def images_for_draft(draft_token):
    """Photos uploaded by a form that has not been submitted yet, oldest first."""
    token = valid_draft_token(draft_token)
    if not token:
        return []
    return db.session.query(RideImage).filter_by(draft_token=token).order_by(RideImage.id.asc()).all()


def _reencode(raw):
    """Decode `raw`, downscale it, and return (jpeg_bytes, width, height).

    Raises RideImageError for anything Pillow can't read or that isn't a format we accept.
    """
    try:
        with Image.open(BytesIO(raw)) as img:
            image_format = img.format
            if image_format not in ALLOWED_FORMATS:
                raise RideImageError(f"Unsupported image format: {image_format or 'unknown'}.")
            # Honour the EXIF orientation flag *before* stripping EXIF, otherwise a photo
            # taken in portrait would be served on its side.
            img = ImageOps.exif_transpose(img)
            # Flatten to RGB: JPEG has no alpha channel, and a transparent PNG saved
            # straight to JPEG raises rather than compositing. White matches the page.
            if img.mode in ("RGBA", "LA", "P"):
                background = Image.new("RGB", img.size, (255, 255, 255))
                converted = img.convert("RGBA")
                background.paste(converted, mask=converted.split()[-1])
                img = background
            elif img.mode != "RGB":
                img = img.convert("RGB")
            img.thumbnail((MAX_DIMENSION, MAX_DIMENSION), Image.LANCZOS)
            out = BytesIO()
            # No exif= argument, so the metadata of the source (GPS, serial, timestamps)
            # is simply not carried over.
            img.save(out, format="JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)
            return out.getvalue(), img.width, img.height
    except RideImageError:
        raise
    except (UnidentifiedImageError, OSError, ValueError) as err:
        # Image.MAX_IMAGE_PIXELS trips as a plain ValueError ("exceeds limit"), a
        # truncated upload as OSError. Neither is worth distinguishing to the user.
        raise RideImageError("That file could not be read as an image.") from err


def prepare_upload(upload):
    """Validate and re-encode one uploaded file, returning a PreparedImage.

    Photos are uploaded one request each (the browser sends them as it gets them), so
    this deliberately handles a single file and lets the caller decide what a rejection
    means for the rest of the batch.
    """
    if upload is None or not upload.filename:
        raise RideImageError("No file was uploaded.")
    # Read one byte past the cap: a stream that still has data at that point is too big,
    # and we learn that without holding the whole thing.
    raw = upload.read(MAX_UPLOAD_BYTES + 1)
    if len(raw) > MAX_UPLOAD_BYTES:
        raise RideImageError(f"'{upload.filename}' is larger than {MAX_UPLOAD_BYTES // (1024 * 1024)} MB.")
    if not raw:
        raise RideImageError(f"'{upload.filename}' is empty.")
    data, width, height = _reencode(raw)
    return PreparedImage(data, width, height)


def store_draft_image(draft_token, prepared, user_id=None):
    """Write one prepared photo to disk under `draft_token`. Returns the saved row.

    Raises RideImageError if the write fails — unlike the ride-submit path, nothing has
    been published yet, so the honest answer to the browser is "that didn't work".
    """
    token = valid_draft_token(draft_token)
    if not token:
        raise RideImageError("Missing upload token.")
    try:
        # Month folders keep any single directory to a manageable number of entries, and
        # make "delete everything older than X" a directory operation if it's ever needed.
        now = datetime.now(timezone.utc)
        rel_dir = f"{now.year:04d}/{now.month:02d}"
        os.makedirs(os.path.join(ride_images_dir(), rel_dir), exist_ok=True)
        # A uuid rather than the uploaded name: the original filename is attacker
        # controlled, may collide, and can itself carry personal information.
        filename = f"{rel_dir}/{uuid.uuid4().hex}.jpg"
        with open(os.path.join(ride_images_dir(), filename), "wb") as handle:
            handle.write(prepared.data)
    except OSError as err:
        logger.exception("Could not write a draft ride photo")
        raise RideImageError("The photo could not be saved. Please try again.") from err

    try:
        row = RideImage(
            draft_token=token,
            filename=filename,
            user_id=user_id,
            width=prepared.width,
            height=prepared.height,
        )
        db.session.add(row)
        db.session.commit()
    except Exception as err:
        db.session.rollback()
        # Leave no orphan file behind for a row that never landed.
        _unlink(filename)
        logger.exception("Could not record a draft ride photo")
        raise RideImageError("The photo could not be saved. Please try again.") from err
    return row


def claim_draft_images(draft_token, d_tag):
    """Attach a submitted form's draft photos to the ride it just created. Never raises.

    Runs after the Nostr publish, because that is when the d tag first exists. Capped
    again here rather than trusting the upload-time check: the token travels through the
    browser, so the only number that matters is the one at claim time.
    """
    token = valid_draft_token(draft_token)
    if not token or not d_tag:
        return []
    try:
        allowance = MAX_IMAGES_PER_RIDE - len(images_for_ride(d_tag))
        rows = images_for_draft(token)[:allowance] if allowance > 0 else []
        for row in rows:
            row.ride_d_tag = d_tag
            row.draft_token = None
        db.session.commit()
        return rows
    except Exception:
        db.session.rollback()
        # The ride is already published; losing its photos is bad but not worth a 500.
        logger.exception("Could not attach draft photos to d_tag=%s", d_tag)
        return []


def delete_ride_image(row):
    """Remove one photo's row and its file. The caller owns the authorisation check."""
    filename = row.filename
    db.session.delete(row)
    db.session.commit()
    # File last: an orphaned file wastes disk, an orphaned row shows a broken image.
    _unlink(filename)


def sweep_stale_drafts():
    """Delete draft photos nobody ever submitted. Never raises.

    Called opportunistically from the upload endpoint rather than from cron: the only
    thing that creates drafts is an upload, so that is exactly when the sweep is due, and
    it keeps this feature from needing a deploy/cron entry of its own.
    """
    try:
        cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - DRAFT_TTL
        rows = (
            db.session.query(RideImage).filter(RideImage.draft_token.isnot(None), RideImage.created_at < cutoff).limit(100).all()
        )
        filenames = [row.filename for row in rows]
        for row in rows:
            db.session.delete(row)
        db.session.commit()
        for filename in filenames:
            _unlink(filename)
        return len(rows)
    except Exception:
        db.session.rollback()
        logger.exception("Could not sweep stale draft ride photos")
        return 0


def _unlink(filename):
    try:
        os.remove(os.path.join(ride_images_dir(), filename))
    except OSError:
        logger.warning("Could not remove ride image file %s", filename)
